
import type { Metadata } from "next";
import { Inter, Montserrat, Cormorant_Garamond } from 'next/font/google'; 
import HeaderContainer from '@/src/components/HeaderContainer/HeaderContainer'
import { Footer } from "../components/Footer/Footer";
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
  display: "swap",
});
const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  style: ['italic'],
  variable: '--font-playfair',
  display: 'swap',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${cormorant.variable} ${montserrat.variable} antialiased`}
      >
        <HeaderContainer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
